package com.finapp.models.enums;

public enum NotificationType {
    BUDGET_ALERT,
    BUDGET_THRESHOLD_70,
    BUDGET_THRESHOLD_85,
    BUDGET_THRESHOLD_95,
    BUDGET_EXCEEDED,
    BUDGET_FORECAST_RISK,
    DAILY_SAFE_LIMIT,
    BUDGET_PERIOD_END,

    GOAL_CONTRIBUTION_DUE,
    GOAL_BEHIND_SCHEDULE,
    GOAL_DEADLINE_RISK,
    GOAL_ALMOST_DONE,
    GOAL_COMPLETED,
    GOAL_PROGRESS,

    LARGE_TRANSACTION,
    UNUSUAL_TRANSACTION,
    CATEGORY_SPIKE,
    NEW_RECURRING_TRANSACTION,
    HABIT_DETECTED,

    SUBSCRIPTION_REMINDER,
    SUBSCRIPTION_RENEWAL,
    SUBSCRIPTION_UNUSED,
    SUBSCRIPTION_DUPLICATE,
    SUBSCRIPTION_PRICE_INCREASE,

    REPORT_READY,
    RECOMMENDATION,
    POSITIVE_PROGRESS,
    WEEKLY_SUMMARY,
    SYSTEM
}
