package com.finapp.models.enums;

public enum NotificationType {
    BUDGET_ALERT,
    BUDGET_THRESHOLD,
    BUDGET_EXCEEDED,
    BUDGET_FORECAST_RISK,
    DAILY_SAFE_LIMIT,
    BUDGET_PERIOD_ENDING,

    GOAL_PROGRESS,
    GOAL_CONTRIBUTION_DUE,
    GOAL_BEHIND_SCHEDULE,
    GOAL_DEADLINE_RISK,
    GOAL_ALMOST_COMPLETED,
    GOAL_COMPLETED,

    HABIT_DETECTED,
    LARGE_TRANSACTION,
    UNUSUAL_TRANSACTION,
    CATEGORY_SPIKE,
    RECURRING_TRANSACTION_DETECTED,

    SUBSCRIPTION_REMINDER,
    SUBSCRIPTION_RENEWAL,
    SUBSCRIPTION_UNUSED,
    SUBSCRIPTION_DUPLICATE,
    SUBSCRIPTION_PRICE_INCREASE,

    REPORT_READY,
    RECOMMENDATION,
    POSITIVE_PROGRESS,
    WEEKLY_SUMMARY,
    SYSTEM
}
