server:
  port: ${SERVER_PORT:8085}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finapp}
    username: ${DB_USERNAME:finapp}
    password: ${DB_PASSWORD:finapp}
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: org.hibernate.type.format.jackson.JacksonJsonFormatMapper

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/finapp}

  data:
    redis:
      repositories:
        enabled: false

app:
  security:
    cors:
      allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:8081,http://127.0.0.1:8081}
